
#.
#Packmakers' control panel for internal recipe compat
[recipes]

	#.
	#.
	#Recipes configs
	[recipes.recipes]

		#.
		#Grinder settings
		[recipes.recipes.grinder]
			#.
			#Destroy item, when it inserted in grinder with wrong recipe speed.
			destroyOnWrongGrinderSpeed = false
			#.
			#Low speed value for grinder crafts, speed_limits = 1.
			#Range: 1 ~ 256
			lowSpeedValue = 16
			#.
			#Medium speed value for grinder crafts, speed_limits = 2.
			#Range: 1 ~ 256
			mediumSpeedValue = 64
			#.
			#Allows sandpaper crafts on belt grinder, when recipes collides belt grinder recipe have priority.
			allowSandpaperPolishingOnGrinder = true
			#.
			#Works only when "allowSandpaperPolishingOnGrinder" is true. Defines speed limits for sandpaper recipes on belt grinder.
			#Range: 0 ~ 3
			speedLimitsForSandpaperPolishingRecipes = 1

		#.
		#Vibrating Table settings
		[recipes.recipes.vibratingTable]
			#.
			#Allows unpacking storage blocks crafts on vibrating table.
			allowUnpackingOnVibratingTable = true
			#.
			#Allows vibrating leaves on vibrating table to get matching drops.
			allowVibratingLeaves = true

		#.
		#Curving Press settings
		[recipes.recipes.curvingPress]
			#.
			#Allows automatic recognize recipes for curving press
			allowAutoCurvingRecipes = true

		#.
		#Helve Hammer settings
		[recipes.recipes.helveHammer]
			#.
			#Helve Hammer will damage Anvil after finishing recipe
			damageAnvilAfterHammeringRecipe = false
			#.
			#Chance of Anvil damaging after finishing recipe
			#Range: 1 ~ 100
			chanceToDamageAnvilAfterHammeringRecipe = 12

#.
#Parameters and abilities of Vintage Improvements's kinetic mechanisms
[kinetics]

	[kinetics.stressValues]

		#.
		#.
		#Fine tune the kinetic stats of individual components
		[kinetics.stressValues.v2]

			#.
			#.
			#[in Stress Units]
			#Configure the individual stress impact of mechanical blocks. Note that this cost is doubled for every speed increase it receives.
			[kinetics.stressValues.v2.impact]
				vibrating_table = 2.0
				helve_kinetic = 8.0
				curving_press = 8.0
				spring_coiling_machine = 4.0
				centrifuge = 2.0
				belt_grinder = 4.0
				vacuum_chamber = 4.0

